import Head from "next/head";
import React from "react";
import { useUsers } from "../hooks";
import styles from "../styles/Home.module.css";

export default function users(props) {
  const { data, isLoading } = useUsers(100);
  if (isLoading) return <div>Loading</div>;
  return (
    <div>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}> Visitors</h1>

        <div>{data && data.map((u) => <li key={u.id}>{u.name}</li>)}</div>
        <div className={styles.grid}></div>
      </main>
    </div>
  );
}
